// Generated by gencpp from file rpi_msgs/ledStatus.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_LEDSTATUS_H
#define RPI_MSGS_MESSAGE_LEDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpi_msgs
{
template <class ContainerAllocator>
struct ledStatus_
{
  typedef ledStatus_<ContainerAllocator> Type;

  ledStatus_()
    : ledNumber(0)
    , ledStatus()  {
    }
  ledStatus_(const ContainerAllocator& _alloc)
    : ledNumber(0)
    , ledStatus(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _ledNumber_type;
  _ledNumber_type ledNumber;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ledStatus_type;
  _ledStatus_type ledStatus;





  typedef boost::shared_ptr< ::rpi_msgs::ledStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpi_msgs::ledStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ledStatus_

typedef ::rpi_msgs::ledStatus_<std::allocator<void> > ledStatus;

typedef boost::shared_ptr< ::rpi_msgs::ledStatus > ledStatusPtr;
typedef boost::shared_ptr< ::rpi_msgs::ledStatus const> ledStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpi_msgs::ledStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpi_msgs::ledStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rpi_msgs::ledStatus_<ContainerAllocator1> & lhs, const ::rpi_msgs::ledStatus_<ContainerAllocator2> & rhs)
{
  return lhs.ledNumber == rhs.ledNumber &&
    lhs.ledStatus == rhs.ledStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rpi_msgs::ledStatus_<ContainerAllocator1> & lhs, const ::rpi_msgs::ledStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rpi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::ledStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::ledStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::ledStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::ledStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::ledStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::ledStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpi_msgs::ledStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae9bed52aabba7ce5ecb3ffd3198f36e";
  }

  static const char* value(const ::rpi_msgs::ledStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae9bed52aabba7ceULL;
  static const uint64_t static_value2 = 0x5ecb3ffd3198f36eULL;
};

template<class ContainerAllocator>
struct DataType< ::rpi_msgs::ledStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpi_msgs/ledStatus";
  }

  static const char* value(const ::rpi_msgs::ledStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpi_msgs::ledStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ledNumber\n"
"string ledStatus\n"
;
  }

  static const char* value(const ::rpi_msgs::ledStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpi_msgs::ledStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ledNumber);
      stream.next(m.ledStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ledStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpi_msgs::ledStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpi_msgs::ledStatus_<ContainerAllocator>& v)
  {
    s << indent << "ledNumber: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ledNumber);
    s << indent << "ledStatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ledStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPI_MSGS_MESSAGE_LEDSTATUS_H
