// Generated by gencpp from file rpi_msgs/runningLedGoal.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_RUNNINGLEDGOAL_H
#define RPI_MSGS_MESSAGE_RUNNINGLEDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpi_msgs
{
template <class ContainerAllocator>
struct runningLedGoal_
{
  typedef runningLedGoal_<ContainerAllocator> Type;

  runningLedGoal_()
    : numberOfRuns(0)  {
    }
  runningLedGoal_(const ContainerAllocator& _alloc)
    : numberOfRuns(0)  {
  (void)_alloc;
    }



   typedef int16_t _numberOfRuns_type;
  _numberOfRuns_type numberOfRuns;





  typedef boost::shared_ptr< ::rpi_msgs::runningLedGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpi_msgs::runningLedGoal_<ContainerAllocator> const> ConstPtr;

}; // struct runningLedGoal_

typedef ::rpi_msgs::runningLedGoal_<std::allocator<void> > runningLedGoal;

typedef boost::shared_ptr< ::rpi_msgs::runningLedGoal > runningLedGoalPtr;
typedef boost::shared_ptr< ::rpi_msgs::runningLedGoal const> runningLedGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpi_msgs::runningLedGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rpi_msgs::runningLedGoal_<ContainerAllocator1> & lhs, const ::rpi_msgs::runningLedGoal_<ContainerAllocator2> & rhs)
{
  return lhs.numberOfRuns == rhs.numberOfRuns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rpi_msgs::runningLedGoal_<ContainerAllocator1> & lhs, const ::rpi_msgs::runningLedGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rpi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::runningLedGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::runningLedGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::runningLedGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc6204d0e7ad4c8a7417cb0d7dd5f9e4";
  }

  static const char* value(const ::rpi_msgs::runningLedGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc6204d0e7ad4c8aULL;
  static const uint64_t static_value2 = 0x7417cb0d7dd5f9e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpi_msgs/runningLedGoal";
  }

  static const char* value(const ::rpi_msgs::runningLedGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"int16 numberOfRuns\n"
;
  }

  static const char* value(const ::rpi_msgs::runningLedGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numberOfRuns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct runningLedGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpi_msgs::runningLedGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpi_msgs::runningLedGoal_<ContainerAllocator>& v)
  {
    s << indent << "numberOfRuns: ";
    Printer<int16_t>::stream(s, indent + "  ", v.numberOfRuns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPI_MSGS_MESSAGE_RUNNINGLEDGOAL_H
