// Generated by gencpp from file rpi_msgs/runningLedFeedback.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_RUNNINGLEDFEEDBACK_H
#define RPI_MSGS_MESSAGE_RUNNINGLEDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpi_msgs
{
template <class ContainerAllocator>
struct runningLedFeedback_
{
  typedef runningLedFeedback_<ContainerAllocator> Type;

  runningLedFeedback_()
    : currentRun(0)  {
    }
  runningLedFeedback_(const ContainerAllocator& _alloc)
    : currentRun(0)  {
  (void)_alloc;
    }



   typedef int16_t _currentRun_type;
  _currentRun_type currentRun;





  typedef boost::shared_ptr< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct runningLedFeedback_

typedef ::rpi_msgs::runningLedFeedback_<std::allocator<void> > runningLedFeedback;

typedef boost::shared_ptr< ::rpi_msgs::runningLedFeedback > runningLedFeedbackPtr;
typedef boost::shared_ptr< ::rpi_msgs::runningLedFeedback const> runningLedFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpi_msgs::runningLedFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rpi_msgs::runningLedFeedback_<ContainerAllocator1> & lhs, const ::rpi_msgs::runningLedFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.currentRun == rhs.currentRun;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rpi_msgs::runningLedFeedback_<ContainerAllocator1> & lhs, const ::rpi_msgs::runningLedFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rpi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff157b86cffbdcb545f0d624dbf7104e";
  }

  static const char* value(const ::rpi_msgs::runningLedFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff157b86cffbdcb5ULL;
  static const uint64_t static_value2 = 0x45f0d624dbf7104eULL;
};

template<class ContainerAllocator>
struct DataType< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpi_msgs/runningLedFeedback";
  }

  static const char* value(const ::rpi_msgs::runningLedFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"int16 currentRun\n"
;
  }

  static const char* value(const ::rpi_msgs::runningLedFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.currentRun);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct runningLedFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpi_msgs::runningLedFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpi_msgs::runningLedFeedback_<ContainerAllocator>& v)
  {
    s << indent << "currentRun: ";
    Printer<int16_t>::stream(s, indent + "  ", v.currentRun);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPI_MSGS_MESSAGE_RUNNINGLEDFEEDBACK_H
