// Generated by gencpp from file rpi_msgs/safetyZoneResponse.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_SAFETYZONERESPONSE_H
#define RPI_MSGS_MESSAGE_SAFETYZONERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpi_msgs
{
template <class ContainerAllocator>
struct safetyZoneResponse_
{
  typedef safetyZoneResponse_<ContainerAllocator> Type;

  safetyZoneResponse_()
    : success(false)
    , message()  {
    }
  safetyZoneResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct safetyZoneResponse_

typedef ::rpi_msgs::safetyZoneResponse_<std::allocator<void> > safetyZoneResponse;

typedef boost::shared_ptr< ::rpi_msgs::safetyZoneResponse > safetyZoneResponsePtr;
typedef boost::shared_ptr< ::rpi_msgs::safetyZoneResponse const> safetyZoneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator1> & lhs, const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator1> & lhs, const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rpi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpi_msgs/safetyZoneResponse";
  }

  static const char* value(const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct safetyZoneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpi_msgs::safetyZoneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpi_msgs::safetyZoneResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPI_MSGS_MESSAGE_SAFETYZONERESPONSE_H
