// Generated by gencpp from file rpi_msgs/safetyZoneRequest.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_SAFETYZONEREQUEST_H
#define RPI_MSGS_MESSAGE_SAFETYZONEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpi_msgs
{
template <class ContainerAllocator>
struct safetyZoneRequest_
{
  typedef safetyZoneRequest_<ContainerAllocator> Type;

  safetyZoneRequest_()
    : zone(0)  {
    }
  safetyZoneRequest_(const ContainerAllocator& _alloc)
    : zone(0)  {
  (void)_alloc;
    }



   typedef int16_t _zone_type;
  _zone_type zone;





  typedef boost::shared_ptr< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct safetyZoneRequest_

typedef ::rpi_msgs::safetyZoneRequest_<std::allocator<void> > safetyZoneRequest;

typedef boost::shared_ptr< ::rpi_msgs::safetyZoneRequest > safetyZoneRequestPtr;
typedef boost::shared_ptr< ::rpi_msgs::safetyZoneRequest const> safetyZoneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator1> & lhs, const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.zone == rhs.zone;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator1> & lhs, const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rpi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5181c81fa8c5c077c8488a708e0aae10";
  }

  static const char* value(const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5181c81fa8c5c077ULL;
  static const uint64_t static_value2 = 0xc8488a708e0aae10ULL;
};

template<class ContainerAllocator>
struct DataType< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpi_msgs/safetyZoneRequest";
  }

  static const char* value(const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 zone\n"
;
  }

  static const char* value(const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct safetyZoneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpi_msgs::safetyZoneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpi_msgs::safetyZoneRequest_<ContainerAllocator>& v)
  {
    s << indent << "zone: ";
    Printer<int16_t>::stream(s, indent + "  ", v.zone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPI_MSGS_MESSAGE_SAFETYZONEREQUEST_H
