// Generated by gencpp from file rpi_msgs/safetyZone.msg
// DO NOT EDIT!


#ifndef RPI_MSGS_MESSAGE_SAFETYZONE_H
#define RPI_MSGS_MESSAGE_SAFETYZONE_H

#include <ros/service_traits.h>


#include <rpi_msgs/safetyZoneRequest.h>
#include <rpi_msgs/safetyZoneResponse.h>


namespace rpi_msgs
{

struct safetyZone
{

typedef safetyZoneRequest Request;
typedef safetyZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct safetyZone
} // namespace rpi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rpi_msgs::safetyZone > {
  static const char* value()
  {
    return "2cf7256a6a834010475f5aab98d139f1";
  }

  static const char* value(const ::rpi_msgs::safetyZone&) { return value(); }
};

template<>
struct DataType< ::rpi_msgs::safetyZone > {
  static const char* value()
  {
    return "rpi_msgs/safetyZone";
  }

  static const char* value(const ::rpi_msgs::safetyZone&) { return value(); }
};


// service_traits::MD5Sum< ::rpi_msgs::safetyZoneRequest> should match
// service_traits::MD5Sum< ::rpi_msgs::safetyZone >
template<>
struct MD5Sum< ::rpi_msgs::safetyZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rpi_msgs::safetyZone >::value();
  }
  static const char* value(const ::rpi_msgs::safetyZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rpi_msgs::safetyZoneRequest> should match
// service_traits::DataType< ::rpi_msgs::safetyZone >
template<>
struct DataType< ::rpi_msgs::safetyZoneRequest>
{
  static const char* value()
  {
    return DataType< ::rpi_msgs::safetyZone >::value();
  }
  static const char* value(const ::rpi_msgs::safetyZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rpi_msgs::safetyZoneResponse> should match
// service_traits::MD5Sum< ::rpi_msgs::safetyZone >
template<>
struct MD5Sum< ::rpi_msgs::safetyZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rpi_msgs::safetyZone >::value();
  }
  static const char* value(const ::rpi_msgs::safetyZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rpi_msgs::safetyZoneResponse> should match
// service_traits::DataType< ::rpi_msgs::safetyZone >
template<>
struct DataType< ::rpi_msgs::safetyZoneResponse>
{
  static const char* value()
  {
    return DataType< ::rpi_msgs::safetyZone >::value();
  }
  static const char* value(const ::rpi_msgs::safetyZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RPI_MSGS_MESSAGE_SAFETYZONE_H
