// Auto-generated. Do not edit!

// (in-package rpi_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class runningLedFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.currentRun = null;
    }
    else {
      if (initObj.hasOwnProperty('currentRun')) {
        this.currentRun = initObj.currentRun
      }
      else {
        this.currentRun = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type runningLedFeedback
    // Serialize message field [currentRun]
    bufferOffset = _serializer.int16(obj.currentRun, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type runningLedFeedback
    let len;
    let data = new runningLedFeedback(null);
    // Deserialize message field [currentRun]
    data.currentRun = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rpi_msgs/runningLedFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ff157b86cffbdcb545f0d624dbf7104e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    int16 currentRun
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new runningLedFeedback(null);
    if (msg.currentRun !== undefined) {
      resolved.currentRun = msg.currentRun;
    }
    else {
      resolved.currentRun = 0
    }

    return resolved;
    }
};

module.exports = runningLedFeedback;
