// Auto-generated. Do not edit!

// (in-package rpi_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class runningLedGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.numberOfRuns = null;
    }
    else {
      if (initObj.hasOwnProperty('numberOfRuns')) {
        this.numberOfRuns = initObj.numberOfRuns
      }
      else {
        this.numberOfRuns = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type runningLedGoal
    // Serialize message field [numberOfRuns]
    bufferOffset = _serializer.int16(obj.numberOfRuns, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type runningLedGoal
    let len;
    let data = new runningLedGoal(null);
    // Deserialize message field [numberOfRuns]
    data.numberOfRuns = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rpi_msgs/runningLedGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dc6204d0e7ad4c8a7417cb0d7dd5f9e4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    int16 numberOfRuns
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new runningLedGoal(null);
    if (msg.numberOfRuns !== undefined) {
      resolved.numberOfRuns = msg.numberOfRuns;
    }
    else {
      resolved.numberOfRuns = 0
    }

    return resolved;
    }
};

module.exports = runningLedGoal;
