(cl:defpackage rpi_msgs-msg
  (:use )
  (:export
   "<LEDSTATUS>"
   "LEDSTATUS"
   "<RUNNINGLEDACTION>"
   "RUNNINGLEDACTION"
   "<RUNNINGLEDACTIONFEEDBACK>"
   "RUNNINGLEDACTIONFEEDBACK"
   "<RUNNINGLEDACTIONGOAL>"
   "RUNNINGLEDACTIONGOAL"
   "<RUNNINGLEDACTIONRESULT>"
   "RUNNINGLEDACTIONRESULT"
   "<RUNNINGLEDFEEDBACK>"
   "RUNNINGLEDFEEDBACK"
   "<RUNNINGLEDGOAL>"
   "RUNNINGLEDGOAL"
   "<RUNNINGLEDRESULT>"
   "RUNNINGLEDRESULT"
  ))

