; Auto-generated. Do not edit!


(cl:in-package rpi_msgs-msg)


;//! \htmlinclude runningLedGoal.msg.html

(cl:defclass <runningLedGoal> (roslisp-msg-protocol:ros-message)
  ((numberOfRuns
    :reader numberOfRuns
    :initarg :numberOfRuns
    :type cl:fixnum
    :initform 0))
)

(cl:defclass runningLedGoal (<runningLedGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <runningLedGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'runningLedGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rpi_msgs-msg:<runningLedGoal> is deprecated: use rpi_msgs-msg:runningLedGoal instead.")))

(cl:ensure-generic-function 'numberOfRuns-val :lambda-list '(m))
(cl:defmethod numberOfRuns-val ((m <runningLedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rpi_msgs-msg:numberOfRuns-val is deprecated.  Use rpi_msgs-msg:numberOfRuns instead.")
  (numberOfRuns m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <runningLedGoal>) ostream)
  "Serializes a message object of type '<runningLedGoal>"
  (cl:let* ((signed (cl:slot-value msg 'numberOfRuns)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <runningLedGoal>) istream)
  "Deserializes a message object of type '<runningLedGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'numberOfRuns) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<runningLedGoal>)))
  "Returns string type for a message object of type '<runningLedGoal>"
  "rpi_msgs/runningLedGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'runningLedGoal)))
  "Returns string type for a message object of type 'runningLedGoal"
  "rpi_msgs/runningLedGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<runningLedGoal>)))
  "Returns md5sum for a message object of type '<runningLedGoal>"
  "dc6204d0e7ad4c8a7417cb0d7dd5f9e4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'runningLedGoal)))
  "Returns md5sum for a message object of type 'runningLedGoal"
  "dc6204d0e7ad4c8a7417cb0d7dd5f9e4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<runningLedGoal>)))
  "Returns full string definition for message of type '<runningLedGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%int16 numberOfRuns~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'runningLedGoal)))
  "Returns full string definition for message of type 'runningLedGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%int16 numberOfRuns~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <runningLedGoal>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <runningLedGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'runningLedGoal
    (cl:cons ':numberOfRuns (numberOfRuns msg))
))
