; Auto-generated. Do not edit!


(cl:in-package rpi_msgs-msg)


;//! \htmlinclude runningLedFeedback.msg.html

(cl:defclass <runningLedFeedback> (roslisp-msg-protocol:ros-message)
  ((currentRun
    :reader currentRun
    :initarg :currentRun
    :type cl:fixnum
    :initform 0))
)

(cl:defclass runningLedFeedback (<runningLedFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <runningLedFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'runningLedFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rpi_msgs-msg:<runningLedFeedback> is deprecated: use rpi_msgs-msg:runningLedFeedback instead.")))

(cl:ensure-generic-function 'currentRun-val :lambda-list '(m))
(cl:defmethod currentRun-val ((m <runningLedFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rpi_msgs-msg:currentRun-val is deprecated.  Use rpi_msgs-msg:currentRun instead.")
  (currentRun m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <runningLedFeedback>) ostream)
  "Serializes a message object of type '<runningLedFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'currentRun)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <runningLedFeedback>) istream)
  "Deserializes a message object of type '<runningLedFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'currentRun) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<runningLedFeedback>)))
  "Returns string type for a message object of type '<runningLedFeedback>"
  "rpi_msgs/runningLedFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'runningLedFeedback)))
  "Returns string type for a message object of type 'runningLedFeedback"
  "rpi_msgs/runningLedFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<runningLedFeedback>)))
  "Returns md5sum for a message object of type '<runningLedFeedback>"
  "ff157b86cffbdcb545f0d624dbf7104e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'runningLedFeedback)))
  "Returns md5sum for a message object of type 'runningLedFeedback"
  "ff157b86cffbdcb545f0d624dbf7104e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<runningLedFeedback>)))
  "Returns full string definition for message of type '<runningLedFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int16 currentRun~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'runningLedFeedback)))
  "Returns full string definition for message of type 'runningLedFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int16 currentRun~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <runningLedFeedback>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <runningLedFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'runningLedFeedback
    (cl:cons ':currentRun (currentRun msg))
))
