; Auto-generated. Do not edit!


(cl:in-package rpi_msgs-msg)


;//! \htmlinclude runningLedResult.msg.html

(cl:defclass <runningLedResult> (roslisp-msg-protocol:ros-message)
  ((finalRun
    :reader finalRun
    :initarg :finalRun
    :type cl:fixnum
    :initform 0))
)

(cl:defclass runningLedResult (<runningLedResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <runningLedResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'runningLedResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rpi_msgs-msg:<runningLedResult> is deprecated: use rpi_msgs-msg:runningLedResult instead.")))

(cl:ensure-generic-function 'finalRun-val :lambda-list '(m))
(cl:defmethod finalRun-val ((m <runningLedResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rpi_msgs-msg:finalRun-val is deprecated.  Use rpi_msgs-msg:finalRun instead.")
  (finalRun m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <runningLedResult>) ostream)
  "Serializes a message object of type '<runningLedResult>"
  (cl:let* ((signed (cl:slot-value msg 'finalRun)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <runningLedResult>) istream)
  "Deserializes a message object of type '<runningLedResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'finalRun) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<runningLedResult>)))
  "Returns string type for a message object of type '<runningLedResult>"
  "rpi_msgs/runningLedResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'runningLedResult)))
  "Returns string type for a message object of type 'runningLedResult"
  "rpi_msgs/runningLedResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<runningLedResult>)))
  "Returns md5sum for a message object of type '<runningLedResult>"
  "6ccad0b1b58e144a35bb45588be3a81e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'runningLedResult)))
  "Returns md5sum for a message object of type 'runningLedResult"
  "6ccad0b1b58e144a35bb45588be3a81e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<runningLedResult>)))
  "Returns full string definition for message of type '<runningLedResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%int16 finalRun~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'runningLedResult)))
  "Returns full string definition for message of type 'runningLedResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%int16 finalRun~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <runningLedResult>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <runningLedResult>))
  "Converts a ROS message object to a list"
  (cl:list 'runningLedResult
    (cl:cons ':finalRun (finalRun msg))
))
